INSERT INTO CATEGORIES (CATEGORY_NAME)
VALUES ('Gaming');

INSERT INTO CATEGORIES (CATEGORY_NAME)
VALUES ('Office');

INSERT INTO USERS (NAME, SURNAME, USERNAME, PASSWORD, EMAIL)
VALUES ('Aslan', 'Qasimov', 'aslan', '12345', 'aslan@gmail.com');

INSERT INTO COMPUTERS (BRAND, MODEL, PRICE, CATEGORY_ID)
VALUES ('HP', 'Victus', 1800, 1);

INSERT INTO COMPUTERS (BRAND, MODEL, PRICE, CATEGORY_ID)
VALUES ('Lenovo', 'IdeaPad', 1500, 2);

INSERT INTO ORDERS (ORDER_DATE, TOTAL_PRICE, STATUS, USER_ID)
VALUES ('2026-07-12', 1800, 'NEW', 1);

INSERT INTO ORDERS (ORDER_DATE, TOTAL_PRICE, STATUS, USER_ID)
VALUES ('2026-07-12', 1500, 'DELIVERED', 1);